server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:${server.port}/eureka
    server:
      enable-self-perservation: false #关闭自我保护（缺省为打开）
      eviction-interval-timer-in-ms: 1000  # 扫描失效服务的间隔时间（缺省为60*1000ms）